name: Comprehensive Codebase Review
description: Comprehensive codebase, architecture, and pipeline review with modernization recommendations
title: "Comprehensive Codebase, Architecture, and Pipeline Review with Modernization Recommendations"
labels: ["review", "architecture", "ci-cd", "modernization"]
assignees:
  - copilot
body:
  - type: textarea
    id: objective
    attributes:
      label: Objective
      description: Purpose of this review
      value: |
        Direct an experienced principal software architect to perform a holistic assessment of this repository. Start by validating guardrails (confirm the repo contains source code and build tooling; stop and report if it is purely documentation). When the review proceeds, require proportional coverage for each primary language or framework, ensure all outputs live under a `copilot-eval` folder, and capture actionable modernization guidance together with risks and remediation next steps.
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: Scope
      description: Areas to be analyzed
      value: |
        - Guardrails: verify the repository includes executable source code plus build tooling (abort if only docs exist); acknowledge and cover each primary language or framework proportionally.
        - Repository intake: map structure, key modules and services, build systems, runtimes, deployment models, functional domains, and major entry points.
        - Code quality & best practices: evaluate architecture, patterns, strengths, anti-patterns, and model topologies with referenced evidence.
        - Dependency & API inventory: catalog external APIs/SDKs (purpose, usage) and third-party libraries/frameworks with versions and upgrade considerations.
        - Testing, security, performance, maintainability: assess strategy, coverage signals, vulnerabilities, compliance, performance factors, documentation, modularity, and onboarding friction.
        - CI/CD & operations: inspect pipelines, automation scripts, IaC, recurring failures, flaky tests, and recommend tooling reliability improvements.
        - Modernization roadmap: flag outdated platforms, suggest upgrade sequencing, quick wins, longer-term initiatives, and cost/impact rationale.
        - Scoring & reporting: assign 1-10 scores for required categories, produce a Mermaid architecture diagram, summarize open improvement issues with links and actions, and close with explicit stakeholder next steps.
        - Special instructions: reference files by relative path, append `copilot-eval` to `.prettierignore` if it exists, generate Chi and logging reviews when applicable (Vue UI or Java code), and ensure all artifacts reside under `copilot-eval/`.
    validations:
      required: true

  - type: textarea
    id: scoring
    attributes:
      label: Scoring Breakdown (1-10 scale)
      description: Score each category
      value: |
        | Category               | Score | Justification |
        |------------------------|-------|---------------|
        | Code Quality           |       |               |
        | Architecture           |       |               |
        | Testing                |       |               |
        | Security               |       |               |
        | Performance            |       |               |
        | Maintainability        |       |               |
        | CI/CD Pipeline         |       |               |
        | Documentation          |       |               |
        | Modernization          |       |               |
        | Dependencies           |       |               |
        | CHI Compliance (if applicable) |       |               |
        | Logging (if applicable)        |       |               |

        *Provide a numeric score (1-10) and concise justification for every relevant dimension. Note conditional categories only when they apply.*
    validations:
      required: true

  - type: textarea
    id: deliverables
    attributes:
      label: Deliverables
      description: Expected outputs
      value: |
        - Narrative findings, strengths, risks → `copilot-eval/summary.md`
        - Architecture overview and functional summary → `copilot-eval/architecture.md`
        - Dependency and external API inventories → `copilot-eval/dependencies.md`
        - Model and data topology → `copilot-eval/model-topology.md`
        - CI/CD health, failure diagnostics, automation gaps → `copilot-eval/ci-cd.md`
        - Recommended code, pipeline, and automation improvements → `copilot-eval/improvements.md`
        - Modernization roadmap with prioritized actions → `copilot-eval/modernization.md`
        - Scoring table with 1-10 ratings and rationales → `copilot-eval/scoring.md`
        - Mermaid architecture diagram source → `copilot-eval/architecture.mmd`
        - Improvement-focused GitHub issue synopsis → `copilot-eval/improvement-issues.md`
        - Chi design system compliance review (only when a Vue UI exists) → `copilot-eval/chi-compliance.md`
        - Logging practices review (only when Java code exists) → `copilot-eval/logging-review.md`

        Place every artifact inside `copilot-eval/`. If a `.prettierignore` file exists, append `copilot-eval` without removing existing entries. Close deliverables with clear next steps or stakeholder questions when risks remain.
    validations:
      required: true

  - type: textarea
    id: additional-notes
    attributes:
      label: Additional Notes
      description: Add any specific areas of concern or focus for this review
      placeholder: Any specific technologies, patterns, or areas to prioritize...
    validations:
      required: false
