name: Comprehensive Codebase Review
description: Comprehensive codebase, architecture, and pipeline review with modernization recommendations
title: "Comprehensive Codebase, Architecture, and Pipeline Review with Modernization Recommendations"
labels: ["review", "architecture", "ci-cd", "modernization"]
assignees:
  - Copilot
body:
  - type: textarea
    id: objective
    attributes:
      label: Objective
      description: Purpose of this review
      value: |
        Conduct a thorough evaluation of the codebase in this repository, assessing best practices, identifying areas of concern, and providing a general critique. This review must include a high-level architectural document and functional summary, API and library dependency inventories, and a model object topology. Examine the build pipeline and CI/CD workflows for health and modernization opportunities, including a root cause analysis of common failures and outdated technologies.
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: Scope
      description: Areas to be analyzed
      value: |
        - Analyze the overall code quality and structure
        - Identify usage (or lack) of best practices for the technology being used
        - Highlight any notable strengths or areas for improvement in the code
        - Provide a high-level architectural document, including a functional summary
        - List all API dependencies
        - List all external library dependencies
        - Provide an organized topology of any model objects
        - Review the build pipeline configuration and CI/CD workflows for health
        - List explanations and root causes for any common CI/CD failures
        - Suggest improvements for code quality, pipeline, or automation
        - Summarize findings of any outdated, old, or antiquated technologies, libraries, or resources, with modernization recommendations
        - Assign a numerical score (1-10) based on the overall evaluation, with justification
        - Generate and include an architecture diagram using Mermaid syntax to visually represent the system architecture and key interactions
        - Summarize all open GitHub issues addressing improvements with details and possible solution steps for each
        - Place all generated output (documents, diagrams, summaries, etc.) under a root folder called `copilot-eval` for organizational clarity
    validations:
      required: true

  - type: textarea
    id: scoring
    attributes:
      label: Scoring Breakdown (1-10 scale)
      description: Score each category
      value: |
        | Category         | Score | Justification |
        |------------------|-------|---------------|
        | Code Quality     |       |               |
        | Architecture     |       |               |
        | Testing          |       |               |
        | Security         |       |               |
        | Performance      |       |               |
        | Maintainability  |       |               |
        | CI/CD Pipeline   |       |               |
        | Documentation    |       |               |
        | Modernization    |       |               |
        | Dependencies     |       |               |

        *Please fill in each category with an appropriate score and justification based on your analysis.*
    validations:
      required: true

  - type: textarea
    id: deliverables
    attributes:
      label: Deliverables
      description: Expected outputs
      value: |
        - Written summary of findings (best practices, concerns, critique) → `copilot-eval/summary.md`
        - High-level architectural document and functional summary → `copilot-eval/architecture.md`
        - Inventories of all API and external library dependencies → `copilot-eval/dependencies.md`
        - Organized model object topology → `copilot-eval/model-topology.md`
        - CI/CD health analysis and failure root cause explanations → `copilot-eval/ci-cd.md`
        - Suggestions for code, pipeline, and automation improvements → `copilot-eval/improvements.md`
        - Modernization recommendations → `copilot-eval/modernization.md`
        - Assigned numerical score (1-10) with rationale → `copilot-eval/scoring.md`
        - Mermaid architecture diagram visualizing the system → `copilot-eval/architecture.mmd`
        - Summary of open GitHub improvement issues with details and solution steps → `copilot-eval/improvement-issues.md`

        All output should be placed under the `copilot-eval` root folder.
        If a `.prettierignore` file exists add the path to the `copilot-eval` folder.
    validations:
      required: true

  - type: textarea
    id: additional-notes
    attributes:
      label: Additional Notes
      description: Add any specific areas of concern or focus for this review
      placeholder: Any specific technologies, patterns, or areas to prioritize...
    validations:
      required: false
