name: Create Copilot Instructions
description: Create comprehensive copilot-instructions.md based on codebase analysis
title: "Create Copilot Instructions"
labels: ["documentation", "enhancement"]
assignees:
  - copilot
body:
  - type: textarea
    id: request
    attributes:
      label: Request
      description: Purpose of this issue
      value: |
        Please create a `copilot-instructions.md` file for this repository under the '.github' root directory. The instructions should be generated based on a thorough analysis of the entire codebase and should provide clear, actionable guidance for GitHub Copilot and future contributors. If a copilot-instructions.md file already exists elsewhere (like in the root of the repo) use it as a basis, update it, and move it under the '.github' folder.
    validations:
      required: true

  - type: textarea
    id: focus-areas
    attributes:
      label: Key Focus Areas
      description: Important aspects to cover
      value: |
        - **Maintain code quality:** Document coding standards, architectural patterns, and best practices that should be followed.
        - **Test coverage:** Specify requirements and expectations for automated testing, including coverage thresholds and locations of tests.
        - **Linting rules:** List and explain all linting and formatting rules to be enforced, referencing configuration files if present (e.g., ESLint, Prettier).
        - **Adherence to existing guidelines:** Summarize and link to any existing documentation for contribution, style guides, review processes, or CI/CD requirements.
    validations:
      required: true

  - type: textarea
    id: requirements
    attributes:
      label: Requirements
      description: Guidelines for creating the instructions
      value: |
        - The `.github/copilot-instructions.md` should be clear, concise, and easily adaptable for use in similar repositories.
        - Review all configuration files, documentation, and code comments for relevant standards.
        - Highlight any repository-specific nuances.
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any additional context or specific requirements for this repository
      placeholder: Any repository-specific considerations...
    validations:
      required: false
