name: Improve Test Coverage Playwright
description: Improve test coverage using Playwright (Typescript and Vue 3)
title: "Improve test coverage using Playwright (Typescript and Vue 3)"
labels: ["testing", "enhancement", "playwright"]
assignees:
  - copilot
body:
  - type: textarea
    id: repository-analysis
    attributes:
      label: Repository Analysis
      description: Primary language and framework information
      value: |
        **Primary Language:** TypeScript using Vue 3
    validations:
      required: true

  - type: textarea
    id: objective
    attributes:
      label: Objective
      description: Goal for test coverage improvement
      value: |
        Improve Playwright test coverage for this repo to ensure comprehensive testing aiming for at least 80% coverage across all categories: statements, branches, functions, and lines. If you cannot achieve this goal of 80% please do your best to improve test coverage as much as possible and explain why you aren't able to exceed 80% coverage if necessary.
    validations:
      required: true

  - type: textarea
    id: instructions
    attributes:
      label: Instructions
      description: Steps to follow
      value: |
        - Review existing test files, if present, to understand current coverage
        - Analyze current test coverage using appropriate tools
    validations:
      required: true

  - type: textarea
    id: general-instructions
    attributes:
      label: General Instructions
      description: PR and testing guidelines
      value: |
        - Create a pull request for the unit test coverage improvements
        - Minimize the number of commits
        - Before starting, check coverage and print the human-readable result in the PR description
        - After completing the work, check coverage and print the human-readable result in the PR description
        - Ensure all tests pass before asking for a review of the PR
        - Do not introduce any secrets or sensitive information in the tests
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Overview of the task
      value: |
        We need to improve the test coverage in our repository to ensure better code quality and reliability. This task involves writing additional unit tests for the existing codebase, identifying untested areas, and ensuring that all critical paths are covered.
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: Tasks
      description: Specific tasks to complete
      value: |
        - Review the current test coverage report to identify areas with insufficient coverage
        - Write unit tests for uncovered or poorly covered code sections
        - Ensure that all critical paths and edge cases are tested
        - Refactor existing tests for better readability and maintainability, if necessary
        - Update the test coverage report and ensure it meets the project's standards
    validations:
      required: true

  - type: textarea
    id: mandates
    attributes:
      label: Mandates
      description: Mandates
      value: |
        - Do not perform synthetic testing or smoke tests.
        - Do not use introspection or other tricks to inflate code coverage without valid unit tests.
        - Do not create tests solely to increase test coverage alone without asserting expectations.        
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: Success criteria
      value: |
        - Test coverage should be increased by at least 50% with a goal of 80% of lines covered
        - All new tests should pass without errors
        - The updated test coverage report should reflect the improvements
    validations:
      required: true

  - type: textarea
    id: current-coverage
    attributes:
      label: Current Coverage Metrics
      description: Paste the current coverage report if available
      placeholder: |
        Statements: X%
        Branches: X%
        Functions: X%
        Lines: X%
    validations:
      required: false

  - type: textarea
    id: areas-of-focus
    attributes:
      label: Specific Areas of Focus
      description: List any specific files, modules, or features that need priority testing
      placeholder: List files or modules that need attention...
    validations:
      required: false
