name: ❓ Question
description: Ask a question about the project
title: "[Question]: "
labels: ["question", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your question! Please provide as much detail as possible to help us assist you.
  
  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: Please describe your question in detail.
    validations:
      required: true
  
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context that might help us understand your question better.
      placeholder: |
        - What are you trying to accomplish?
        - What have you tried so far?
        - Any relevant code, configuration, or examples
    validations:
      required: false
  
  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Any other information that might be helpful
      placeholder: Links, screenshots, or other relevant details
    validations:
      required: false
